name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - name: Run tests and collect coverage
      run: pytest --cov .
    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)